name: diacare_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0  # For SVG images if needed
  google_sign_in: ^6.1.0  # Add this for Google Sign-In


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/blood.png  # Add the path to your logo image
    - images/google_logo.png  # Add the Google logo image
    - images/profile.png  # Add the profile image